# Generated by Django 6.0 on 2025-12-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash of file content for duplicate detection', max_length=64),
        ),
    ]
